### ISSUE TITLE
Strong name Pomelo.Extensions.Caching.MySql.dll

### ISSUE THREAD

**Issue by pmachapman** [PomeloFoundation/Caching-MySQL#23]
Can we please have Pomelo.Extensions.Caching.MySql.dll strong named?

This will fix the warning I am receiving when compiling a strong named project, referencing this package:

`Warning CS8002 Referenced assembly 'Pomelo.Extensions.Caching.MySql, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Comment by ChaosEngine** [comment]
I'll into it next week.

**Comment by ChaosEngine** [comment]
Related discussion(s):
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/603.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md
Reuse some kind of global Pomelo Key (if any exists) ?

**Comment by pmachapman** [comment]
It looks like there is a global key here? https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/Pomelo.snk

**Comment by ChaosEngine** [comment]
> It looks like there is a global key here? https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/Pomelo.snk

Yes, most likely I'll be using it. Stay tuned.

**Comment by ChaosEngine** [comment]
@pmachapman just out of curiosity, which framework version your main app uses?

**Comment by pmachapman** [comment]
@ChaosEngine .Net 5.0. The project is at https://github.com/pmachapman/GoTo.Bible/tree/master/GoToBible.Web/Server. I've also documented how to use the Caching Provider at https://github.com/pmachapman/GoTo.Bible/wiki/Caching-with-MySQL.

**Comment by ChaosEngine** [comment]
Fixing with #24 and https://github.com/PomeloFoundation/Caching-MySQL/releases/tag/v2.1.1, please test

**Comment by pmachapman** [comment]
I have just tested on .Net 5.0 with MySQL 8.0.23 (downloaded via NuGet), and it works great - thanks!
