### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by SrgAleRin** [PomeloFoundation/Caching-MySQL#25]
Is it possible to support multiple TargetFrameworks?
It would be great if Pomelo.Extensions.Caching.MySql targeted .NET Standard 2.0 as well.
We are currently using Pomelo.Extensions.Caching.MySql version 2.0.3 with .NET Framework 4.8, and we need the latest version of MySqlConnector, but unfortunately we cannot just update it due to their breaking changes in version 1.0.0,
and we cannot update Pomelo.Extensions.Caching.MySql because now it targets .net standard 2.1

**Comment by ChaosEngine** [comment]
I just got back from vacation. I will look into this in the following days.

**Comment by ChaosEngine** [comment]
published 2.1.2 release
