### ISSUE TITLE
Documentation for distributed cache provider and tools

### ISSUE THREAD

**Issue by elfuerte211** [PomeloFoundation/Caching-MySQL#42]
It would be nice to have instructions in the readme file on how to use set up MySQL as the distributed cache backing store. Also, instructions on how use the config tools to create the necessary database table.

**Comment by ChaosEngine** [comment]
Resolved with https://github.com/PomeloFoundation/Caching-MySQL/pull/86

**Comment by ChaosEngine** [comment]
@elfuerte211 please verify

**Comment by elfuerte211** [comment]
Looks good! @ChaosEngine
